name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: "Railway environment"
        required: true
        type: choice
        options:
          - dev
          - production
      ref:
        description: "Git ref to deploy"
        required: true
        default: "dev"
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.18.0
          cache: npm

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --project "${{ vars.RAILWAY_PROJECT_ID }}" --environment "${{ inputs.environment }}" --service "ShelfBox" --ci
